## Set the input data directory and data format (csv or sql)
input_data_dir : "/home/arr65/vs30_data_input_data/sql"
input_data_format : "sql"

## Set the output directory
output_dir : "/home/arr65/vs30_data_output/"

## Set the number of processors to use
n_procs : 7

## Set input data filtering parameters
min_CPT_separation_dist_m : 0.1
max_num_same_depth_values : 1
min_allowed_data_value : -0.2
max_num_allowed_repeated_digits : 3
min_allowed_max_depth_m : 5
min_allowed_depth_span_m : 5
